name: kashr
description: "Personal finance app with a focus on privacy and open source."
publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.2+3

environment:
  sdk: '>=3.8.0<4.0.0'

dependencies:
  flutter:
    sdk: flutter

  archive: ^4.0.7
  collection: ^1.19.1
  crypto: ^3.0.7
  decimal: ^3.2.4
  dio: ^5.9.0
  file_picker: ^10.3.8
  fl_chart: ^1.1.1
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^10.0.0
  freezed_annotation: ^3.1.0
  go_router: ^17.0.1
  http: ^1.6.0
  intl: ^0.20.2
  jiffy: ^6.4.4
  json_annotation: ^4.9.0
  local_auth: ^3.0.0
  logger: ^2.6.2
  meta: ^1.17.0
  package_info_plus: ^9.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  pointycastle: ^4.0.0
  provider: ^6.1.5+1
  retrofit: ^4.9.1
  sqlite3: ^3.1.1
  string_similarity: ^2.1.1
  url_launcher: ^6.3.2
  uuid: ^4.5.2
  xml: ^6.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.10.4
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  freezed: ^3.2.3
  go_router_builder: ^4.1.3
  json_serializable: ^6.11.2
  retrofit_generator: 10.2.0 # note 10.2.1 is bugged which is why we not have the caret ^

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo-transparent.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
